### PR TITLE
Small MonoMod fix

### PR DESCRIPTION
**Pull request by psyGamer**
Small fix, since i accidently used `Hook` instead of `ILHook`.
Also not properly privatizes HookGen, so that it's also not included when publishing the launcher.

### CODE REVIEW

**Comment by psyGamer** [comment]
I actually just found an issue with hooking constructors, so wait with merging this for a bit.

**Comment by jasminegamedev** [comment]
I might be a bit confused by your comment. Is this ready to go now, or are you still working on it?

**Comment by psyGamer** [comment]
Its ready. I meant the commit i pushed right after.

**Comment by jasminegamedev** [comment]
looks good to me

**Pull request merged**
